### ISSUE TITLE
Improve docker scripts name convection

### ISSUE THREAD

**Issue by dirkgruending** [AndreWeiner/phd_notebooks#12]
It may be more suitable to rename the docker-scripts to "runContainer.sh" and "attachToContainer.sh" in all repositories.

**Comment by AndreWeiner** [comment]
I decided for the current naming because I believe it to be more intuitive for somebody who is not familiar with containerization. _runContainer_ makes technical sense, but without knowledge about Docker, I would assume that I need this script to run simulations or notebooks. Actually, the script executes something similar to the installation step in the classical software workflow. The second script _startNotebooks_ starts the container if it was stopped (the container must have been created before) and then executes an interactive shell in the container. Again, I find _startNotebooks_ more user friendly since its purpose is immediately clear.
